DUMMY_LISTINGS = [
    {
        "property_id": 1,
        "title": "Private furnished room near AHU",
        "description": "Fully furnished private room with WiFi, AC, utilities included and parking. 5 minutes from AHU.",
        "price": 150,
        "location": "Near AHU",
        "room_type": "single",
        "availability_status": "available",
    },
    {
        "property_id": 2,
        "title": "Shared student room in Ma'an center",
        "description": "Shared room with two beds, internet included, near shops and public transportation.",
        "price": 90,
        "location": "Ma'an Center",
        "room_type": "shared",
        "availability_status": "available",
    },
    {
        "property_id": 3,
        "title": "Studio apartment near university",
        "description": "Studio apartment with air conditioning, security cameras, parking, and private bathroom.",
        "price": 220,
        "location": "Near University",
        "room_type": "studio",
        "availability_status": "available",
    },
    {
        "property_id": 4,
        "title": "Occupied single room",
        "description": "Single room near AHU with WiFi.",
        "price": 130,
        "location": "Near AHU",
        "room_type": "single",
        "availability_status": "occupied",
    },
]


DUMMY_STUDENTS = [
    {
        "id": 1,
        "name": "Ahmad",
        "gender": "male",
        "prefs": {
            "sleep": "late",
            "smoke": "no",
            "clean": 4,
            "noise": 2,
            "social": 3,
            "budget": 150,
            "pets_allowed": False,
            "study": 4,
        },
    },
    {
        "id": 2,
        "name": "Omar",
        "gender": "male",
        "prefs": {
            "sleep": "early",
            "smoke": "no",
            "clean": 3,
            "noise": 1,
            "social": 2,
            "budget": 130,
            "pets_allowed": False,
            "study": 5,
        },
    },
    {
        "id": 3,
        "name": "Khaled",
        "gender": "male",
        "prefs": {
            "sleep": "late",
            "smoke": "yes",
            "clean": 2,
            "noise": 4,
            "social": 5,
            "budget": 180,
            "pets_allowed": True,
            "study": 2,
        },
    },
    {
        "id": 4,
        "name": "Moath",
        "gender": "male",
        "prefs": {
            "sleep": "late",
            "smoke": "no",
            "clean": 5,
            "noise": 2,
            "social": 3,
            "budget": 160,
            "pets_allowed": False,
            "study": 4,
        },
    },
    {
        "id": 5,
        "name": "Sarah",
        "gender": "female",
        "prefs": {
            "sleep": "early",
            "smoke": "no",
            "clean": 5,
            "noise": 1,
            "social": 3,
            "budget": 140,
            "pets_allowed": False,
            "study": 5,
        },
    },
]